<a href="https://colab.research.google.com/github/iitdpooja/Deep-Learning-/blob/main/tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#import torch
#!nvidia-smi
import numpy as np
X = np.arange(24).reshape(2, 3, 4)
#print(X)

A = np.arange(20).reshape(5, 4)
B = A.copy()
print(A)
print('Addition of Matrix is:', A+B)
print('multiplication of Matrix is:',A*B)
a=2
print('shape:', (a+X).shape)
print('sum of matrix elements: ', A.sum())
A_sum_axis0 = A.sum(axis=0) # gives sum of columns
print('Sum of 0 axis elements: ',A_sum_axis0)
print('Dimension of 0 axis: ',A_sum_axis0.shape)

A_sum_axis1 = A.sum(axis=1) # gives sum of rows
print('Sum of 1 axis elements: ',A_sum_axis1)
print('Dimension of 1 axis: ',A_sum_axis1.shape)
print(A.mean())
print(A.size)
print(A.mean(axis=0), A.sum(axis=0) / A.shape[0])
sum_A = A.sum(axis=1, keepdims=True) #keepdims to keep number of axis unchanged
print(sum_A)
print(A / sum_A) #we can divide A by sum_A with broadcasting
print(A.cumsum(axis=0))
x = np.arange(4)
y = np.ones(4)
print(np.dot(x,y))
print(np.sum(x * y)) # elementwise multiplication plus sum gives dot product
print(A.shape, x.shape, np.dot(A, x))
B = np.ones(shape=(4, 3))
print(np.dot(A, B))



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Addition of Matrix is: [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]]
multiplication of Matrix is: [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]
 [256 289 324 361]]
shape: (2, 3, 4)
sum of matrix elements:  190
Sum of 0 axis elements:  [40 45 50 55]
Dimension of 0 axis:  (4,)
Sum of 1 axis elements:  [ 6 22 38 54 70]
Dimension of 1 axis:  (5,)
9.5
20
[ 8.  9. 10. 11.] [ 8.  9. 10. 11.]
[[ 6]
 [22]
 [38]
 [54]
 [70]]
[[0.         0.16666667 0.33333333 0.5       ]
 [0.18181818 0.22727273 0.27272727 0.31818182]
 [0.21052632 0.23684211 0.26315789 0.28947368]
 [0.22222222 0.24074074 0.25925926 0.27777778]
 [0.22857143 0.24285714 0.25714286 0.27142857]]
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]
 [24 28 32 36]
 [40 45 50 55]]
6.0
6.0
(5, 4) (4,) [ 14  38  62  86 110]
[[ 6.  6.  6.]
 [22. 22. 22.]
 [38. 38. 38.]
 [54. 54. 54.]
 [70. 70. 70.]]
